name: Streaming CI/CD

on:
  push:
    branches:
      - main

jobs:
  # Build authentication service (Spring)
  build-authentication:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: |
          cd Authentication
          mvn clean install

  # Build FileSystem service (Spring)
  build-filesystem:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: |
          cd FileSystem
          mvn clean install

  # Build Upload service (Spring)
  build-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: |
          cd UploadVideo
          mvn clean install
  

  # Build Node.js service
  build-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd streaming_app
          npm install



  # Deploy to Docker Hub
  deploy-docker:
    needs: [build-authentication, build-filesystem, build-upload, build-node]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push images
        run: |
          cd Authentication
          docker build -t ${{ secrets.DOCKER_USERNAME }}/authentication-service .
          docker push ${{ secrets.DOCKER_USERNAME }}/authentication-service

          cd ../FileSystem
          docker build -t ${{ secrets.DOCKER_USERNAME }}/filesystem-service .
          docker push ${{ secrets.DOCKER_USERNAME }}/filesystem-service

          cd ../UploadVideo
          docker build -t ${{ secrets.DOCKER_USERNAME }}/upload-service .
          docker push ${{ secrets.DOCKER_USERNAME }}/upload-service

          cd ../streaming_app
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-service .
          docker push ${{ secrets.DOCKER_USERNAME }}/node-service